#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mount -t tmpfs media /media
mount -t tmpfs mnt /mnt
#mkdir -p /media/hdd
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# mdev
echo "[rcS] starting mdev"
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

echo "[rcS] starting mountall"
/etc/init.d/mountall start

# for start from power off
/etc/mdev/ttyUSB-check.sh

echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		#DHCP=$(grep -c dhcp /etc/network/interfaces)
		#if [ "$DHCP" -eq "1" ]; then
		#	echo "Starting dhcp"
		#	/etc/init.d/udhcpc start
		#fi
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"
insmod /lib/modules/$(uname -r)/extra/e4hd_1.ko
insmod /lib/modules/$(uname -r)/extra/e4hd_2.ko
insmod /lib/modules/$(uname -r)/extra/e4hd_3.ko
insmod /lib/modules/$(uname -r)/extra/e4hd_4.ko

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi

# rcS.local
if [ -e /var/etc/rcS.local ]; then 
	/var/etc/rcS.local
fi

