#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mount -t tmpfs media /media
mount -t tmpfs mnt /mnt
#mkdir -p /media/hdd
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

# mdev
echo > /dev/mdev.log
echo > /dev/mdev.seq
echo "/sbin/mdev" >/proc/sys/kernel/hotplug
touch /dev/.udev
[ -d "/sys/kernel" ] || mount sysfs /sys -t sysfs
[ -L "/dev/fd" ] || ln -sf /proc/self/fd /dev/fd
mdev -s

echo "[rcS] starting mountall"
/etc/init.d/mountall start

#
if [ -e /sys/class/net/lo ]; then
	/sbin/ifconfig lo up
fi
if [ -e /sys/class/net/eth0 ]; then
	/sbin/ifconfig eth0 up
fi
if [ -e /sys/class/net/eth1 ]; then
	/sbin/ifconfig eth1 up
fi
if [ -e /sys/class/net/sys0 ]; then
	/sbin/ifconfig sys0 up
fi

#
echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		#DHCP=$(grep -c dhcp /etc/network/interfaces)
		#if [ "$DHCP" -eq "1" ]; then
		#	echo "Starting dhcp"
		#	/etc/init.d/udhcpc start
		#fi
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"

insmod /lib/modules/stb-core.ko
insmod /lib/modules/helper.ko
insmod /lib/modules/lcd.ko
/etc/init.d/usbtftdisplay.sh
insmod /lib/modules/tu1216.ko
insmod /lib/modules/cxd1981.ko
insmod /lib/modules/cu1216mk3.ko
insmod /lib/modules/max4397.ko
insmod /lib/modules/lnb_ctrl.ko
insmod /lib/modules/bcm4506.ko
insmod /lib/modules/alps_bsbe1.ko
insmod /lib/modules/alps_bsbe1_c01a.ko
insmod /lib/modules/alps_bsbe2.ko
insmod /lib/modules/bcm4501.ko
insmod /lib/modules/fpga.ko
insmod /lib/modules/bcm7400.ko
insmod /lib/modules/dreambox_rc2.ko
insmod /lib/modules/dreambox_keyboard.ko

echo 255 > /proc/stb/fp/oled_brightness
echo "Booting... DDT" > /dev/dbox/oled0

#/bin/initfb $(sed -n 's/osd_resolution=//p' /var/tuxbox/config/neutrino.conf)

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi

#
until false
do
	/usr/bin/titan /var/etc/titan/titan.cfg
	rtv=$?
	echo "titan ended <- RTV: " $rtv
	case "$rtv" in
		1)
		   echo "SHUTDOWN"
		   init 0;;
		2)
		   echo "REBOOT"
		   init 6;;
		3)
		   echo "RESTART";;
		*) 
		   echo "ERROR"
		   init 6;;
      	esac
done

